apiVersion: v1
kind: Namespace
metadata:
  name: gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: gateway-system
  annotations:
    cert-manager.io/cluster-issuer: vault-issuer
spec:
  gatewayClassName: eg
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - group: ""
        kind: Secret
        name: homelab-gateway-tls
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-gateway-tls
  namespace: gateway-system
spec:
  secretName: homelab-gateway-tls
  commonName: "*.lab.example.com"
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
  dnsNames:
  - "*.lab.example.com"




