apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: truenas-nfs-secret
  namespace: kube-system
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/truenas
  refreshAfter: 1h
  destination:
    name: truenas-nfs-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        driver-config-file.yaml:
          text: |
            driver: freenas-api-nfs
            httpConnection:
              protocol: https
              host: REDACTED
              port: 443
              apiKey: "{{ index .Secrets "api-key" }}"
              allowInsecure: true
              apiVersion: 2
            zfs:
              datasetParentName: tank/k8s/nfs
              detachedSnapshotsDatasetParentName: tank/k8s/nfs-snapshots
              datasetEnableQuotas: true
              datasetEnableReservation: false
              datasetPermissionsMode: "0777"
            nfs:
              shareHost: "10.100.20.2"
              shareAlldirs: false
              shareAllowedNetworks:
                - 10.100.20.0/24