apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: truenas-iscsi-secret
  namespace: kube-system
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/truenas
  refreshAfter: 1h
  destination:
    name: truenas-iscsi-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        driver-config-file.yaml:
          text: |
            driver: freenas-api-iscsi
            httpConnection:
              protocol: https
              host: REDACTED
              port: 443
              apiKey: "{{ index .Secrets "api-key" }}"
              allowInsecure: true
              apiVersion: 2
            zfs:
              datasetParentName: tank/k8s/iscsi
              detachedSnapshotsDatasetParentName: tank/k8s/iscsi-snapshots
              zvolCompression: lz4
              zvolEnableReservation: false
              zvolBlocksize: 16K
            iscsi:
              targetPortal: "REDACTED:3260"
              targetGroups:
                - targetGroupPortalGroup: 1
                  targetGroupInitiatorGroup: 1
                  targetGroupAuthType: None