appName: envoy-gateway
chart: gateway-helm
namespace: envoy-gateway-system
repoURL: oci://registry-1.docker.io/envoyproxy/gateway-helm
syncWave: '-5'
valuesFile: k8s/apps/envoy-gateway/overlays/spoke/values.yaml
version: v1.8.1
