apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: fleet-secrets
  namespace: fleet
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/fleet
  refreshAfter: 1h
  destination:
    name: fleet-secrets
    create: true
    overwrite: true
