apiVersion: v1
kind: Namespace
metadata:
  name: authentik
  labels:
    homelab.example.com/inject-ca: enabled
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
  labels:
    homelab.example.com/inject-ca: enabled
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    homelab.example.com/inject-ca: enabled
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  labels:
    homelab.example.com/inject-ca: enabled
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    homelab.example.com/inject-ca: enabled
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
  labels:
    homelab.example.com/inject-ca: enabled
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    homelab.example.com/inject-ca: enabled
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    goldilocks.fairwinds.com/enabled: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: garage
  labels:
    homelab.example.com/inject-ca: enabled
    goldilocks.fairwinds.com/enabled: "true"
