apiVersion: garage.rajsingh.info/v1beta1
kind: GarageAdminToken
metadata:
  name: garage-admin-token
  namespace: garage
spec:
  clusterRef:
    name: garage
  neverExpires: true
  secretTemplate:
    name: garage-admin-token
    tokenKey: adminToken
