enableMonitoring: false
enableCertManager: true

env:
  - name: VAULT_ADDR
    value: https://vault.vault.svc.cluster.local:8200
  - name: VAULT_CACERT
    value: /vault/ca/ca.crt

volumes:
  - name: vault-ca
    secret:
      secretName: root-ca

volumeMounts:
  - name: vault-ca
    mountPath: /vault/ca
    readOnly: true
