apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: capmox-system
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: capmox-system
spec:
  vaultConnectionRef: vso/vault-hub
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-role
    serviceAccount: vault-auth
    tokenExpirationSeconds: 3600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: spoke-proxmox-credentials
  namespace: capmox-system
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/proxmox
  refreshAfter: 24h
  destination:
    name: spoke-proxmox-credentials
    create: true
    overwrite: true
    labels:
      platform.ionos.com/secret-type: "proxmox-credentials"
    transformation:
      excludeRaw: true
      templates:
        url:
          text: '{{ index .Secrets "url" }}'
        token:
          text: '{{ index .Secrets "token" }}'
        secret:
          text: '{{ index .Secrets "secret" }}'
