apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: default
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: default
spec:
  vaultConnectionRef: vso/vault-hub
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-role
    serviceAccount: vault-auth
    tokenExpirationSeconds: 3600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: spoke-talos
  namespace: default
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/spoke/talos-secrets
  refreshAfter: 24h
  destination:
    name: spoke-talos
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        bundle:
          text: |
            cluster:
              id: "{{ index .Secrets "cluster-id" }}"
              secret: "{{ index .Secrets "cluster-secret" }}"
            secrets:
              bootstraptoken: "{{ index .Secrets "bootstrap-token" }}"
              secretboxencryptionsecret: "{{ index .Secrets "secretbox-encryption-secret" }}"
            trustdinfo:
              token: "{{ index .Secrets "trustd-token" }}"
            certs:
              etcd:
                crt: "{{ index .Secrets "etcd-crt" }}"
                key: "{{ index .Secrets "etcd-key" }}"
              k8s:
                crt: "{{ index .Secrets "k8s-crt" }}"
                key: "{{ index .Secrets "k8s-key" }}"
              k8saggregator:
                crt: "{{ index .Secrets "k8s-aggregator-crt" }}"
                key: "{{ index .Secrets "k8s-aggregator-key" }}"
              k8sserviceaccount:
                key: "{{ index .Secrets "k8s-serviceaccount-key" }}"
              os:
                crt: "{{ index .Secrets "os-crt" }}"
                key: "{{ index .Secrets "os-key" }}"



