fullnameOverride: kube-prometheus-stack

grafana:
  enabled: false

prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 10GB
    storageSpec:
      emptyDir:
        medium: ""
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    probeSelectorNilUsesHelmValues: false
    externalLabels:
      cluster: hub
    remoteWrite:
      - url: https://prometheus-remote-write.lab.example.com/api/v1/write
        tlsConfig:
          insecureSkipVerify: true
    resources:
      requests:
        cpu: 100m
        memory: 512Mi
      limits:
        cpu: 500m
        memory: 1Gi

alertmanager:
  alertmanagerSpec: {}
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'cluster']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
        - matchers:
            - alertname = Watchdog
          receiver: 'null'
    receivers:
      - name: 'null'

nodeExporter:
  enabled: true

kube-state-metrics:
  enabled: true

prometheusOperator:
  enabled: true
  admissionWebhooks:
    enabled: true
    certManager:
      enabled: true
  tls:
    enabled: true

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false
    configReloaders: true
    general: true
    k8sContainerCpuUsageSecondsTotal: true
    k8sContainerMemoryCache: true
    k8sContainerMemoryRss: true
    k8sContainerMemorySwap: true
    k8sContainerResource: true
    k8sPodOwner: true
    kubeApiserverAvailability: true
    kubeApiserverBurnrate: true
    kubeApiserverHistogram: true
    kubeApiserverSlos: true
    kubeControllerManager: false
    kubeProxy: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: true
    kubelet: true
    kubePrometheusGeneral: true
    kubePrometheusNodeRecording: true
    kubernetesApps: true
    kubernetesResources: true
    kubernetesStorage: true
    kubernetesSystem: true
    node: true
    nodeExporterAlerting: true
    nodeExporterRecording: true
    prometheus: true
    prometheusOperator: true
