appName: external-secrets
chart: external-secrets
namespace: external-secrets
repoURL: https://charts.external-secrets.io
syncWave: '-5'
valuesFile: k8s/apps/external-secrets/overlays/hub/values.yaml
version: 0.14.0
