apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: argocd-sso-secret
  namespace: argocd
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/argocd
  refreshAfter: 1h
  destination:
    name: argocd-sso-secret
    create: true
    overwrite: true
    labels:
      app.kubernetes.io/part-of: argocd