apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kyverno-vso-rbac.yaml
  - sync-ca-bundles.yaml
  - sync-harbor-db-password.yaml
  - require-run-as-non-root.yaml
  - require-resources.yaml
