apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: arc-github-app-secret
  namespace: arc-runners
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/arc
  refreshAfter: 1h
  destination:
    name: arc-github-app-secret
    create: true
    overwrite: true
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: harbor-runner-secret
  namespace: arc-runners
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/harbor-runner
  refreshAfter: 1h
  destination:
    name: harbor-runner-secret
    create: true
    overwrite: true

