apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      group: cilium.io
      version: v2
      kind: CiliumLoadBalancerIPPool
      name: dynamic-pool
    patch: |
      - op: replace
        path: /spec/blocks/0/cidr
        value: 10.100.60.0/24
  - target:
      group: cilium.io
      version: v2
      kind: CiliumBGPClusterConfig
      name: opnsense-bgp-cluster-config
    patch: |
      - op: replace
        path: /spec/bgpInstances/0/name
        value: "instance-65010"
      - op: replace
        path: /spec/bgpInstances/0/localASN
        value: 65010
      - op: replace
        path: /spec/bgpInstances/0/peers/0/peerAddress
        value: "10.100.10.1"
