apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: tetragon-elastic-agent-credentials
  namespace: kube-system
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/tetragon-elastic-agent-spoke
  refreshAfter: 24h
  destination:
    name: tetragon-elastic-agent-credentials
    create: true
    overwrite: true
