apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: crossplane-system
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: crossplane-system
spec:
  vaultConnectionRef: vso/vault-hub
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: vso-role
    serviceAccount: vault-auth
    tokenExpirationSeconds: 3600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: crossplane-proxmox-credentials
  namespace: crossplane-system
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/proxmox
  refreshAfter: 24h
  destination:
    name: crossplane-proxmox-credentials
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        credentials:
          text: |
            {
              "endpoint": "{{ index .Secrets "url" }}",
              "api_token": "{{ index .Secrets "token" }}={{ index .Secrets "secret" }}",
              "insecure": "true"
            }
---
apiVersion: proxmoxbpg.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: proxmox-hub
spec:
  credentials:
    source: Secret
    secretRef:
      name: crossplane-proxmox-credentials
      namespace: crossplane-system
      key: credentials
---
apiVersion: proxmoxbpg.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: proxmox-hub-ns
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: crossplane-proxmox-credentials
      namespace: crossplane-system
      key: credentials

