apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: garage
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: garage
spec:
  vaultConnectionRef: vso/vault-hub
  method: jwt
  mount: jwt-spoke
  jwt:
    role: vso-garage-role
    serviceAccount: vault-auth
    tokenExpirationSeconds: 3600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: garage-secret
  namespace: garage
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/garage
  refreshAfter: 24h
  destination:
    name: garage-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        rpcSecret:
          text: '{{ index .Secrets "rpcSecret" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: garage-admin-token
  namespace: garage
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/garage-admin
  refreshAfter: 24h
  destination:
    name: garage-admin-token
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        adminToken:
          text: '{{ index .Secrets "adminToken" }}'
