apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: apps-cluster
  namespace: argocd
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/apps-cluster
  refreshAfter: 24h
  destination:
    name: apps-cluster
    create: true
    overwrite: true
    labels:
      argocd.argoproj.io/secret-type: cluster
    transformation:
      excludeRaw: true
      templates:
        name:
          text: "apps"
        server:
          text: "https://[REDACTED]:6443"
        config:
          text: |
            {
              "bearerToken": "{{ index .Secrets "token" }}",
              "tlsClientConfig": {
                "insecure": false,
                "caData": "{{ index .Secrets "ca-crt" }}"
              }
            }
