apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: https://vault.lab.example.com:32200
    path: pki_int/sign/internal-homelab
    caBundle: REDACTED
    auth:
      kubernetes:
        role: cert-manager-role
        mountPath: /v1/auth/jwt-spoke
        serviceAccountRef:
          name: cert-manager
          audiences:
          - https://10.100.30.10:6443
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: admin@example.com
    privateKeySecretRef:
      name: letsencrypt-production-private-key
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-api-token
              key: api-token
