apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cert-manager-auth-delegator.yaml
  - issuers.yaml
  - vaultauth.yaml
  - vso-secret-cloudflare.yaml
  - vso-secret-root-ca.yaml
