apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik-route.yaml
  - certificate.yaml
  - vaultauth.yaml
  - vso-secret-authentik.yaml
configMapGenerator:
  - name: blueprint-argocd
    files:
      - argocd.yaml=blueprints/argocd.yaml
    options:
      disableNameSuffixHash: true
  - name: blueprint-harbor
    files:
      - harbor.yaml=blueprints/harbor.yaml
    options:
      disableNameSuffixHash: true
  - name: blueprint-groups
    files:
      - groups.yaml=blueprints/groups.yaml
    options:
      disableNameSuffixHash: true
  - name: blueprint-kanidm
    files:
      - kanidm.yaml=blueprints/kanidm.yaml
    options:
      disableNameSuffixHash: true
  - name: blueprint-grafana
    files:
      - grafana.yaml=blueprints/grafana.yaml
    options:
      disableNameSuffixHash: true
  - name: blueprint-fleet
    files:
      - fleet.yaml=blueprints/fleet.yaml
    options:
      disableNameSuffixHash: true


