apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/authentik
  refreshAfter: 1h
  destination:
    name: authentik-secrets
    create: true
    overwrite: true
    transformation:
      excludeRaw: false
      templates:
        AUTHENTIK_SECRET_KEY:
          text: '{{ index .Secrets "secret-key" }}'
        AUTHENTIK_BOOTSTRAP_PASSWORD:
          text: '{{ index .Secrets "bootstrap-password" }}'
        AUTHENTIK_BOOTSTRAP_TOKEN:
          text: '{{ index .Secrets "bootstrap-token" }}'
        AUTHENTIK_POSTGRESQL__PASSWORD:
          text: '{{ index .Secrets "postgresql-password" }}'
        postgresql-password:
          text: '{{ index .Secrets "postgresql-password" }}'
        ARGOCD_OIDC_CLIENT_SECRET:
          text: '{{ index .Secrets "argocd-client-secret" }}'
        HARBOR_OIDC_CLIENT_SECRET:
          text: '{{ index .Secrets "harbor-oidc-client-secret" }}'
        KANIDM_OIDC_CLIENT_SECRET:
          text: '{{ index .Secrets "kanidm-client-secret" }}'
        KANIDM_CA_CERT:
          text: '{{ index .Secrets "kanidm-ca-cert" }}'
        GRAFANA_OIDC_CLIENT_SECRET:
          text: '{{ index .Secrets "grafana-client-secret" }}'