apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: monitoring
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: vault-auth
  namespace: monitoring
spec:
  vaultConnectionRef: vso/vault-hub
  method: jwt
  mount: jwt-spoke
  jwt:
    role: vso-monitoring-role
    serviceAccount: vault-auth
    tokenExpirationSeconds: 3600
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/grafana
  refreshAfter: 1h
  destination:
    name: grafana-admin-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        admin-user:
          text: '{{ index .Secrets "admin-user" }}'
        admin-password:
          text: '{{ index .Secrets "admin-password" }}'
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: grafana-oauth-secret
  namespace: monitoring
spec:
  vaultAuthRef: vault-auth
  mount: secret
  type: kv-v2
  path: homelab/grafana-oauth
  refreshAfter: 1h
  destination:
    name: grafana-oauth-secret
    create: true
    overwrite: true
    transformation:
      excludeRaw: true
      templates:
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
          text: '{{ index .Secrets "client-secret" }}'
